import = ["/home/vizee/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 13

[font.normal]
family = "IntelOne Mono"

[scrolling]
history = 10000

[window.dimensions]
columns = 96
lines = 32

[window.padding]
x = 2
y = 2
