local o=vim.o
local wo=vim.wo
local bo=vim.bo

o.encoding = 'utf-8'
o.fileencoding = 'utf-8'
o.backup = false
o.swapfile = false
o.confirm = true
o.smartindent = true
o.cindent = true
o.autoindent = true
o.shiftwidth = 4
bo.shiftwidth = 4
o.tabstop = 4
o.softtabstop = 4
bo.expandtab = true
o.expandtab = true
o.backspace = 'indent,eol,start'
wo.signcolumn = 'no'
o.laststatus = 2
o.mouse = 'a'
o.selection = 'exclusive'
wo.number = true
o.ruler = true
wo.cursorline = true
o.wrap = false
o.showcmd = true
o.showmode = false
-- o.breakindent = true
o.hlsearch = false
o.incsearch = true
o.autoread = false
o.completeopt = 'menu,menuone,noselect'
o.pumheight = 16
o.wildmenu = true
-- o.listchars = 'tab:»■,trail:■,space:·'
-- o.list = true
o.splitbelow = true
o.splitright = true
o.background = 'dark'
o.termguicolors = true
o.shortmess = vim.o.shortmess .. 'c'
