vim.o.encoding = 'utf-8'
vim.o.fileencoding = 'utf-8'
vim.o.backup = false
vim.o.swapfile = false
vim.o.confirm = true
vim.o.smartindent = true
vim.o.cindent = true
vim.o.autoindent = true
vim.o.shiftwidth = 4
vim.bo.shiftwidth = 4
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.bo.expandtab = true
vim.o.expandtab = true
vim.o.backspace = 'indent,eol,start'
vim.wo.signcolumn = 'no'
vim.o.laststatus = 2
vim.o.mouse = 'a'
vim.o.selection = 'exclusive'
vim.wo.number = true
vim.o.ruler = true
vim.wo.cursorline = true
vim.o.wrap = false
vim.o.showcmd = true
vim.o.showmode = false
-- vim.o.breakindent = true
vim.o.hlsearch = false
vim.o.incsearch = true
vim.o.autoread = true
vim.o.completeopt = 'menu,menuone,noselect'
vim.o.pumheight = 16
vim.o.wildmenu = true
-- vim.o.listchars = 'tab:»■,trail:■,space:·'
-- vim.o.list = true
vim.o.splitbelow = true
vim.o.splitright = true
vim.o.background = 'dark'
vim.o.termguicolors = true
vim.o.shortmess = vim.o.shortmess .. 'c'
